name: Rust CD

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt-get install libgtk-3-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Build
        run: cargo build --release
      
      - name: Rename Binary
        if: matrix.os != 'windows-latest' && matrix.os != 'macos-latest'
        run: mv target/release/shadow_box target/release/${{ matrix.os }}_shadow_box
      - name: Rename Binary MacOS
        if: matrix.os == 'macos-latest'
        run: mv target/release/shadow_box target/release/${{ matrix.os }}_shadow_box.app
      - name: Rename Binary Windows
        if: matrix.os == 'windows-latest'
        run: move target\release\shadow_box.exe target\release\${{ matrix.os }}_shadow_box.exe # Stupid windows

      - name: Compress Binary
        if: matrix.os != 'windows-latest' && matrix.os != 'macos-latest'
        run: tar -cf ${{ matrix.os }}-release.zip target/release/${{ matrix.os }}_shadow_box
      - name: Compress Binary MacOS
        if: matrix.os == 'macos-latest'
        run: tar -cf ${{ matrix.os }}-release.zip target/release/${{ matrix.os }}_shadow_box.app
      - name: Compress Binary Windows
        if: matrix.os == 'windows-latest'
        run: tar -cf ${{ matrix.os }}-release.zip target\release\${{ matrix.os }}_shadow_box.exe # Stupid windows

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.os }}-release.zip