name: Rust CD

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup
        run: echo "BIN=shadow_box.exe" >> $GITHUB_ENV && echo "TARGET=shadow_box.exe" >> $GITHUB_ENV
        if: matrix.os == 'windows-latest'

      - name: Setup
        run: echo "BIN=shadow_box" >> $GITHUB_ENV && echo "TARGET=shadow_box.app" >> $GITHUB_ENV
        if: matrix.os == 'macos-latest'

      - name: Setup
        run: echo "BIN=shadow_box" >> $GITHUB_ENV && echo "TARGET=shadow_box" >> $GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - run: sudo apt-get install libgtk-3-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Build
        run: cargo build --release
      
      - name: Rename Binary
        if: matrix.os != 'windows-latest'
        run: mv target/release/${{ env.BIN }} target/release/${{ env.TARGET }}

      - name: Rename Binary Windows
        if: matrix.os == 'windows-latest'
        run: move target\release\${{ env.BIN }} target\release\${{ env.TARGET }} # Stupid windows


      - name: Zip Binary
        uses: montudor/action-zip@v1
        with:
          args: zip -qq ${{ matrix.os }}-release.zip target/release/${{ env.TARGET }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.os }}-release.zip