name: Rust CD

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt-get install libgtk-3-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Build
        run: cargo build --release
      

      - name: Release MacOs
        if: matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          # Is this really what it's called on macos?
          files: target/release/shadow_box
      - name: Release Windows
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/shadow_box.exe
      - name: Release Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/shadow_box
